package:
  name: intan2kwik
  version: "0.0.2"

source:
  git_rev: v0.0.2
  git_url: https://github.com/zekearneodo/intan2kwik.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pyinstrument

about:
  home: https://github.com/zekearneodo/intan2kwik/tree/multirec
  license: BSD
  license_file: LICENSE