package:
  name: intan2kwik
  version: "0.0.3"

source:
  git_rev: v0.0.3
  git_url: https://github.com/zekearneodo/intan2kwik.git

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.4
    - h5py >=2.9
    - tqdm >=4.28
    - numba >=0.4
    - pandas >=0.23
  run:
    - python
    - numpy >=1.4
    - h5py >=2.9
    - tqdm >=4.28
    - numba >=0.4
    - pandas >=0.23

test:
  imports:
    - intan2kwik

about:
  home: https://github.com/zekearneodo/intan2kwik/tree/multirec
  license: BSD
  license_file: LICENSE